name: 02 - Workflow Events

on: 
    push:
    pull_request:
    schedule:
        - cron: '*/5 0 * * *'
         # This will trigger the workflow every day at midnight
    workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: show the trigger
              run: echo "I've been triggered by a(n) ${{ github.event_name}} event"