name : 04 - Using Actions
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        #checkout the code
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: '24.x'
        # Install dependencies of our react app
            - name: Install dependenciesgit a
              run: npm ci
              working-directory: 04-using-actions/react-app
        # Run automated tests
            - name: Run Unit tests
              run: npm run test
              working-directory: 04-using-actions/react-app